library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://www.gizbot.com/best-selling-phones/#samsung-galaxy-a04s-9380'
web <- read_html(url)
View(web)
hi=paths_allowed(url)
mobile_Name <- web %>% html_nodes('.gizbot-prod-title') %>% html_text()
View(mobile_Name)
Camere <- web %>% html_nodes('.gizbot-specs-highlight-list li:nth-child(1)') %>% html_text()
View(Camere)
Price <- web %>% html_nodes('.gizbot-prod-price') %>% html_text()
View(Price)
data_7= data.frame(mobile_Name,Camere,Price)
View(data_7)
write.csv(data_7,"mobie-list.csv")
